---
# tasks file for samba_setup
- name: Install Samba server
  dnf:
    name: samba
    state: present

- name: Ensuring samba shared directory exists
  file:
    path: "{{ samba_share_path }}"
    setype: samba_share_t
    state: directory
  become: true

- name: Create Samba configuration file
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: restart samba

- name: Starting Samba service
  service:
    name: smb
    enabled: true
    state: started

- name: Placing test file into shared directory
  file:
    path: "{{ samba_share_path }}/hello"
    state: touch
    setype: samba_share_t

- name: install semanage
  package:
    name: policycoreutils-python-utils
    state: present

- name: Set new fcontext for file
  sefcontext:
    target: "{{ samba_share_path }}(/.*)?"
    setype: "samba_share_t"
    state: present
  notify: SELinux file context for Samba share
