---
- name: Configure Samba server and firewall
  hosts: filesharing 
  become: true
  gather_facts: true

  vars:
    allowed_services:
      - ssh
      - samba
    allowed_ports:
      - 4312
    firewall_zone_name: testzone4
    host_ip: "{{ ansible_facts['default_ipv4']['address'] }}"
    host_name: "{{ ansible_facts['hostname'] }}"
    samba_username: guest
    samba_password: 

  roles:
    - samba_setup

  tasks:
    - name: "Create a new firewall zone named {{ firewall_zone_name }}"
      firewalld:
        zone: "{{ firewall_zone_name }}"
        state: present
        permanent: true

    - name: "Set default firewall policy on zone {{ firewall_zone_name }} to reject"
      firewalld:
        zone: "{{ firewall_zone_name }}"
        rich_rule: 'rule family="ipv4" source address="0.0.0.0" reject'
        permanent: true
        state: enabled

    - name: Add allowed service to firewall
      firewalld:
        zone: "{{ firewall_zone_name }}"
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ allowed_services }}"

    - name: Add allowed ports to firewall
      firewalld:
        zone: "{{ firewall_zone_name }}"
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
      loop: "{{ allowed_ports }}"

    - name: Reloading firewalld service
      systemd:
        name: firewalld
        state: restarted

    - name: "Ensuring {{ firewall_zone_name }} zone is selected"
      command:
        cmd: firewall-cmd --set-default-zone={{ firewall_zone_name }}

- name: Mounting share on control node
  hosts: localhost
  become: no
  vars:
    share_directory_name: shareFinal
    share_ip: 10.0.2.10
  tasks:
    - name: "Ensuring /data/{{ share_directory_name }} directory exists"
      become: true
      file:
        path: /data/{{ share_directory_name }}
        state: directory

    - name: Ensuring mount.cifs package is installed on control node
      ansible.builtin.dnf:
        name: cifs-utils
        state: present
      become: true

    - name: Mount samba share on control node
      become: no
      mount:
        src: //{{ share_ip }}/share
        path: /data/{{ share_directory_name }}
        fstype: cifs
        opts: "guest,noserverino"
        state: mounted
